version: '3.4'

services:
  db:
    image: mysql
    container_name: kma-news-db
    environment:
      - "MYSQL_DATABASE=${DATABASE_NAME}"
      - "MYSQL_USER=${DATABASE_USERNAME}"
      - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}"
      - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
    volumes:
      - appdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - db-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kma-news-pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - db-network
    restart: always
    ports:
      - 3456:80
  cache:
    image: redis:5-alpine
    container_name: kma-news-cache
    volumes:
      - appcache:/data
    networks:
      - redis-network
    restart: always
    ports:
      - 6379:6379

volumes:
  appdata: null
  appcache: null

networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
