version: '3.4'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    container_name: kma-news-elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9201:9200'
      - '9301:9300'
    networks:
      - es-network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    container_name: kma-news-kibana
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - es-network
  db:
    image: mysql
    container_name: kma-news-db
    environment:
      - "MYSQL_DATABASE=${DATABASE_NAME}"
      - "MYSQL_USER=${DATABASE_USERNAME}"
      - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}"
      - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
    volumes:
      - appdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    networks:
      - db-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kma-news-pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - db-network
    restart: always
    ports:
      - 3456:80
  cache:
    image: redis:5-alpine
    container_name: kma-news-cache
    volumes:
      - appcache:/data
    networks:
      - redis-network
    restart: always
    ports:
      - 6379:6379

volumes:
  appdata: null
  appcache: null
  esdata: null

networks:
  db-network:
    driver: bridge
  redis-network:
    driver: bridge
  es-network:
    driver: bridge
